# Neural network methods

Author: Gaurav Vaidya

## Learning objectives
* Understand what a neural network is and how it can be used.
* Implement a neural network to label data based on multiple input features.
* Understand when a neural network might be useful and when it might be worse than other methods.
* Learn where to learn more about neural networks.

## Learn deeply
[Artificial Neural Networks (ANNs)](https://en.wikipedia.org/wiki/Artificial_neural_network) and [deep learning](https://en.wikipedia.org/wiki/Deep_learning) are currently getting a lot of interest, both as a subject of research and as a tool for analyzing datasets. ANNs are similar to feature crosses, except that thanks to something called [backpropagation](https://en.wikipedia.org/wiki/Backpropagation), an ANN is able to choose its own features based on the testing data. A lot of the other advantages of ANNs are related specifically to interpreting visual and auditory data, which we won't be doing today, but I'll point you some resources to learn about [convolutional neural networks](https://en.wikipedia.org/wiki/Convolutional_neural_network) yourself.

### Units

ANNs are designed as *layers* of *units* (or nodes, or artificial neurons). Units were initially designed based on how biological neurons function, but they're best thought of as individual *feature-crosses*. Each unit focuses on a particular aspect of the layer underneath it, and then summarizing that information for the layer above it. How does it do this?

Every unit has a *weight* and a *bias*, and so is effectively doing a linear regression on the incoming data to obtain an output. But doing multiple times will just look for linear relationships in the data. To look for non-linear relationships, we need to add a non-linear function: we feed the output of the unit through an *activation function*.

ANNs used to use the same sigmoid function we saw before, but these days the [rectified linear unit (ReLU) function](https://en.wikipedia.org/wiki/Rectifier_(neural_networks)) has become much more popular. It simply returns zero when the real output value is less than zero. This non-linearity can be used by the ANN to distinguish data that is not linearly separable.

![ReLU and softmax rectifiers](800px-Rectifier_and_softplus_functions.svg.png )

### Layers

![A diagram showing input, output and hidden layers in an ANN](../nb-images/colored_neural_network.svg.png)

Every neural network has three layers:

* An input layer, where each unit corresponds to a particular input feature. In our example today, this will be various aspects of a forest plot, but it could be categorical data, continuous data, or even colour values from images.
* An output layer. In many ANNs, the output layer will consist of a single label. In our example today, we will be classifying each forest plot into one of seven types, and so we will have seven output units, one for each type.
* A hidden layer. Without a hidden layer, an ANN could only pick up linear relationships: how changes in the input layer correspond to values in the output layer. Thanks to the hidden layer, an ANN can also pick up non-linear relationships, where different groups of input values need to be treated differently to get the correct response on the output layer.

Putting it all together, we end up with a type of ANN called a *multilayer perceptron (MLP) network*, which looks like the following:

![A visualization of a multi-layer perceptron (MLP) from the Scikit-learn manual](../nb-images/multilayerperceptron_network.png)

[Google's Machine Learning course](https://developers.google.com/machine-learning/crash-course/introduction-to-neural-networks/anatomy) puts this very nicely: "Stacking nonlinearities on nonlinearities lets us model very complicated relationships between the inputs and the predicted outputs. In brief, each layer is effectively learning a more complex, higher-level function over the raw inputs."

### Backpropagation

The heart of neural networks is [backpropagation algorithms](https://en.wikipedia.org/wiki/Backpropagation), which are an efficient way to 

In effect, an ANN is trained by:
1. Setting all weights and biases randomly.
2. For each row in the test data:
    1. Set the input units to the input features.
    2. Use unit weights and biases, passing through the activation function, to calculate the output value of each unit -- right through to the output units.
    3. Use a loss function to Compare the output units with the expected output
    4. Use a backpropagation algorithm to update all the weights and biases to reduce the loss.
    
Google has a [nice visual explanation](https://google-developers.appspot.com/machine-learning/crash-course/backprop-scroll/) of backpropagation. [More detailed explanations](http://neuralnetworksanddeeplearning.com/chap2.html) are also available.
    
### When backpropagation goes wrong

* Vanishing gradients: when weights for lower levels (closer to the input) become very small, gradients become very small too, making it hard or impossible to train these layers. The ReLU activation function can help prevent vanishing gradients.

* Exploding gradients: when weights become very large, the gradients for lower layers can become very large, making it hard for these gradients to converge. Batch normalization can help prevent exploding gradients, as can lowering the learning rate.

* Dead ReLU units: once the weighted sum for a ReLU activation function falls below 0, the ReLU unit can get stuck -- without an output, it doesn't contribute to the network output, and gradients can't flow through it in backpropagation. Lowering the learning rate can help keep ReLU units from dying.

* Dropout regularization: in this form of regularization, a proportion of unit activations are randomly dropped out. This prevents overfitting and so helps create a better model.

## So what do we need?
To create an ANN, we need to choose:
1. The number of input units (= the number of input features)
2. The number of output units:
    - When we are using the ANN to classify, we generally set the number of output units to the number of possible labels
    - When we are using the ANN to calculate a regression, we generally only need a single output unit.
3. The number of hidden layers
    - More hidden layers allows for more complex models -- which, as you've learned, also increases your risk of overfitting! So you want to go for the simplest model that meets your needs.
4. A loss function (the scikit-learn classes we use always use [logistic loss or cross-entropy loss](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.log_loss.html))
4. The solver to use
5. The regularization protocol

Note that these are the [hyperparameters](https://en.wikipedia.org/wiki/Hyperparameter_(machine_learning)) of our model: we can adjust these to improve how good our model is at predicting new values.

## Reminders of the ground rules
* Always have training data (used to train the ANN) and testing data (used to test how well the ANN might work against data it has never seen before).
* Never, ever, ever, ever, *ever* let the ANN see testing data while training!

## ANN for regression: TODO

In [28]:
from sklearn import datasets
help(datasets.load_diabetes)

Help on function load_diabetes in module sklearn.datasets.base:

load_diabetes(return_X_y=False)
    Load and return the diabetes dataset (regression).
    
    ==============      ==================
    Samples total       442
    Dimensionality      10
    Features            real, -.2 < x < .2
    Targets             integer 25 - 346
    ==============      ==================
    
    Read more in the :ref:`User Guide <diabetes_dataset>`.
    
    Parameters
    ----------
    return_X_y : boolean, default=False.
        If True, returns ``(data, target)`` instead of a Bunch object.
        See below for more information about the `data` and `target` object.
    
        .. versionadded:: 0.18
    
    Returns
    -------
    data : Bunch
        Dictionary-like object, the interesting attributes are:
        'data', the data to learn, 'target', the regression target for each
        sample, 'data_filename', the physical location
        of diabetes data csv dataset, and 'target_fil

In [44]:
diabetes = datasets.load_diabetes()

from sklearn.utils import shuffle
diabetes_data = shuffle(diabetes.data)
print("First entry from diabetes: ", diabetes_data[0])
print("Shape of diabetes: ", diabetes_data.shape)

First entry from diabetes:  [ 0.06713621 -0.04464164 -0.06117437 -0.04009932 -0.02633611 -0.02448686
  0.03391355 -0.03949338 -0.05615757 -0.05906719]
Shape of diabetes:  (442, 10)


In [50]:
test_data = diabetes.data[0:42]
test_labels = diabetes.target[0:42]

train_data = diabetes.data[42:]
train_labels = diabetes.target[42:]

In [61]:
from sklearn.neural_network import MLPRegressor

clf = MLPRegressor(
    solver='adam',  # The solver to use
    alpha=1e-5,     # The L2 regularization rate: higher values increase cost for larger weights
    hidden_layer_sizes=(100,20),
                    # 
                    # Note that we don't need to specify input and output neuron numbers: MLPClassifier
                    # determines this based on the shape of the features and labels being fitted.
    batch_size='auto',
    verbose=True,
    early_stopping=True
)
clf.fit(train_data, train_labels)

Iteration 1, loss = 14608.89611676
Validation score: -3.519580
Iteration 2, loss = 14601.20954810
Validation score: -3.517277
Iteration 3, loss = 14593.57886363
Validation score: -3.515019
Iteration 4, loss = 14586.27267163
Validation score: -3.512825
Iteration 5, loss = 14579.10410784
Validation score: -3.510664
Iteration 6, loss = 14571.88346063
Validation score: -3.508499
Iteration 7, loss = 14564.73183699
Validation score: -3.506305
Iteration 8, loss = 14557.43467248
Validation score: -3.504100
Iteration 9, loss = 14550.14729699
Validation score: -3.501958
Iteration 10, loss = 14543.15319922
Validation score: -3.499909
Iteration 11, loss = 14536.53182686
Validation score: -3.497920
Iteration 12, loss = 14529.76952600
Validation score: -3.495897
Iteration 13, loss = 14523.12920888
Validation score: -3.493813
Iteration 14, loss = 14516.14404975
Validation score: -3.491670
Iteration 15, loss = 14509.07554133
Validation score: -3.489463
Iteration 16, loss = 14501.72610559
Validation sc

Validation score: 0.080995
Iteration 184, loss = 2753.44585656
Validation score: 0.095469
Iteration 185, loss = 2705.80106407
Validation score: 0.109325
Iteration 186, loss = 2661.31672917
Validation score: 0.122631
Iteration 187, loss = 2618.40848051
Validation score: 0.135382
Iteration 188, loss = 2577.11781844
Validation score: 0.147580
Iteration 189, loss = 2536.48484047
Validation score: 0.159192
Iteration 190, loss = 2498.78011885
Validation score: 0.170288
Iteration 191, loss = 2461.72431823
Validation score: 0.180861
Iteration 192, loss = 2428.64401470
Validation score: 0.191003
Iteration 193, loss = 2395.04902464
Validation score: 0.200622
Iteration 194, loss = 2362.25847004
Validation score: 0.209736
Iteration 195, loss = 2333.96432134
Validation score: 0.218472
Iteration 196, loss = 2304.30621923
Validation score: 0.226745
Iteration 197, loss = 2277.89386145
Validation score: 0.234644
Iteration 198, loss = 2252.43891490
Validation score: 0.242141
Iteration 199, loss = 2227.3

/usr/lib/python3/dist-packages/sklearn/neural_network/multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPRegressor(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=True, epsilon=1e-08,
       hidden_layer_sizes=(100, 20), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=True, warm_start=False)

In [60]:
clf.score(scaled_test_data, test_labels)

0.25701869403045385

## ANN for classification: what sort of forest is this?
Let's jump in with a dataset called [Covertype](https://archive.ics.uci.edu/ml/datasets/Covertype), where we try to predict forest cover type based on a number of features of a 30x30m area of forest as follows:

| Column | Feature | Units | Description | How measured |
|---|--------|-------|-------------|--------------|
| 1 | Aspect | degrees azimuth | Aspect in degrees azimuth | Quantitative |
| 2 | Slope | degrees | Slope in degrees | Quantitative |
| 3 | Horizontal_Distance_To_Hydrology | meters | Horz Dist to nearest surface water features | Quantitative |
| 4 | Vertical_Distance_To_Hydrology | meters | Vert Dist to nearest surface water features | Quantitative |
| 5 | Horizontal_Distance_To_Roadways | meters | Horz Dist to nearest roadway | Quantitative |
| 6 | Hillshade_9am | 0 to 255 index | Hillshade index at 9am, summer solstice | Quantitative |
| 7 | Hillshade_Noon | 0 to 255 index | Hillshade index at noon, summer soltice | Quantitative |
| 8 | Hillshade_3pm | 0 to 255 index | Hillshade index at 3pm, summer solstice | Quantitative |
| 9 | Horizontal_Distance_To_Fire_Points | meters | Horz Dist to nearest wildfire ignition points | Quantitative |
| 10-14 | Wilderness_Area | 4 binary columns with 0 (absence) or 1 (presence) | Which wilderness area this plot is in | Qualitative |
| 14-54 | Soil_Type | 40 binary columns with 0 (absence) or 1 (presence) | Soil Type designation | Qualitative |

Using this information, we are trying to classify each 30x30m plot as one of seven forest types.

This dataset is built into Scikit, so we can use it to download and load the dataset for use.

In [2]:
from sklearn import datasets
help(datasets.fetch_covtype)

Help on function fetch_covtype in module sklearn.datasets.covtype:

fetch_covtype(data_home=None, download_if_missing=True, random_state=None, shuffle=False, return_X_y=False)
    Load the covertype dataset (classification).
    
    Download it if necessary.
    
    =================   ============
    Classes                        7
    Samples total             581012
    Dimensionality                54
    Features                     int
    =================   ============
    
    Read more in the :ref:`User Guide <covtype_dataset>`.
    
    Parameters
    ----------
    data_home : string, optional
        Specify another download and cache folder for the datasets. By default
        all scikit-learn data is stored in '~/scikit_learn_data' subfolders.
    
    download_if_missing : boolean, default=True
        If False, raise a IOError if the data is not locally available
        instead of trying to download the data from the source site.
    
    random_state : int, Rand

So we don't need to provide any arguments, but it warns us that it may need to download this dataset. It also describes the the returned dataset object will have the following properties:
- .data: a numpy array with the features.
- .target: a numpy array with the target labels. Note that each plot is classified into only one of these values.
- .DESCR: describe this forest covertype.

In [3]:
covtype = datasets.fetch_covtype(shuffle=True)
print("Data: ", covtype.data)
print("Data shape: ", covtype.data.shape) # Describe the size of this array

Data:  [[2670.  108.   12. ...    0.    0.    0.]
 [3204.  253.   12. ...    0.    0.    0.]
 [3039.  320.   16. ...    0.    0.    0.]
 ...
 [2806.   43.    9. ...    0.    0.    0.]
 [3066.  283.    6. ...    0.    0.    0.]
 [3225.  208.   28. ...    0.    0.    0.]]
Data shape:  (581012, 54)


In [19]:
print("Target: ", covtype.target)
print("Target shape: ", covtype.target.shape)

Target:  [3 1 1 ... 1 2 1]
Target shape:  (581012,)


In [20]:
print("Description: ", covtype.DESCR)

Description:  .. _covtype_dataset:

Forest covertypes
-----------------

The samples in this dataset correspond to 30×30m patches of forest in the US,
collected for the task of predicting each patch's cover type,
i.e. the dominant species of tree.
There are seven covertypes, making this a multiclass classification problem.
Each sample has 54 features, described on the
`dataset's homepage <http://archive.ics.uci.edu/ml/datasets/Covertype>`__.
Some of the features are boolean indicators,
while others are discrete or continuous measurements.

**Data Set Characteristics:**

    =================   ============
    Classes                        7
    Samples total             581012
    Dimensionality                54
    Features                     int
    =================   ============

:func:`sklearn.datasets.fetch_covtype` will load the covertype dataset;
it returns a dictionary-like object
with the feature matrix in the ``data`` member
and the target values in ``target``.
The data

## Training data for training, testing data for testing, and validation data for validation.


In [21]:
# Out of 581,012 data entries, let's hold back:
# - 250,000 records as our test dataset
# - remaining records as our training dataset

test_data = covtype.data[0:250_000]
test_labels = covtype.target[0:250_000]

train_data = covtype.data[250_000:]
train_labels = covtype.target[250_000:]

print("Validation data shape: ", validation_data.shape)
print("Validation labels shape: ", validation_labels.shape)

print("Test data shape: ", test_data.shape)
print("Test labels shape: ", test_labels.shape)

print("Training data shape: ", train_data.shape)
print("Training labels shape: ", train_labels.shape)

Validation data shape:  (50000, 54)
Validation labels shape:  (50000,)
Test data shape:  (250000, 54)
Test labels shape:  (250000,)
Training data shape:  (281012, 54)
Training labels shape:  (281012,)


Our data is ready for processing. But remember that we have a variety of different input types: binary (0, 1), continuous in small ranges (0-255) and in large ranges (elevations). Before we process this data, we should normalize them into a standard range.

In [22]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# scaler = MinMaxScaler()
scaler = StandardScaler()

# Figure out how to scale all the input features in the training dataset.
scaler.fit(train_data)
scaled_train_data = scaler.transform(train_data)
print(scaled_train_data[0])

# Also tranform our validation and testing data in the same way.
scaled_test_data = scaler.transform(test_data)
print(scaled_test_data[0])

[ 1.60736862e+00  1.26976625e+00  2.52424211e+00 -1.32789752e-01
 -8.46317415e-01  5.45818884e-01 -3.70587203e+00 -7.77004916e-01
  2.17874024e+00 -8.66734546e-02  1.10618082e+00 -2.32878738e-01
 -8.77654257e-01 -2.60891433e-01 -7.33790197e-02 -1.13756645e-01
 -9.06824489e-02 -1.47164828e-01 -5.28596572e-02 -1.06780531e-01
 -1.36044010e-02 -1.83896215e-02 -4.50039975e-02 -2.44733925e-01
 -1.47354014e-01 -2.33743604e-01 -1.75417877e-01 -3.15815220e-02
 -1.88641977e-03 -7.04798023e-02 -7.70864687e-02 -5.74366014e-02
 -8.33979573e-02 -1.25961739e-01 -3.82249167e-02 -2.47644451e-01
 -3.31516804e-01 -1.94359553e-01 -2.76708817e-02 -6.70314648e-02
 -4.31396443e-02 -4.12782423e-02 -4.99658577e-01 -2.33963654e-01
 -2.14121142e-01 -3.14156848e-01 -2.90124367e-01 -5.24519154e-02
 -5.69983904e-02 -1.57848582e-02 -2.34162292e-02 -1.65615860e-01
  6.39371431e+00 -1.23519671e-01]
[ 1.13253983e+00 -2.93736903e-01  2.54632485e-01 -5.64809237e-01
 -1.70261524e+00 -1.11786676e+00  1.22878378e+00  1.8417

## Classifying among multiple categories

Having multiple output units usually would result in each unit being considered independently, allowing you to assign multiple labels for a particular input (for instance, a single image might be classified as containing both a cloud as well as a bird). However, we use scikit-learn's [MLPClassifier](https://scikit-learn.org/stable/modules/neural_networks_supervised.html#classification), which automatically uses *softmax* to treat labels as exclusive to each other.

### The power of softmax

As based on [](https://developers.google.com/machine-learning/crash-course/multi-class-neural-networks/softmax)

TODO

In [26]:
from sklearn.neural_network import MLPClassifier

clf = MLPClassifier(
    solver='adam',  # The solver to use
    alpha=1e-5,     # The L2 regularization rate: higher values increase cost for larger weights
    hidden_layer_sizes=(100),
                    # 
                    # Note that we don't need to specify input and output neuron numbers: MLPClassifier
                    # determines this based on the shape of the features and labels being fitted.
    batch_size='auto',
    verbose=True,
    early_stopping=True
)
clf.fit(scaled_train_data, train_labels)

Iteration 1, loss = 0.66653904
Validation score: 0.749413
Iteration 2, loss = 0.56445348
Validation score: 0.765035
Iteration 3, loss = 0.53419656
Validation score: 0.777169
Iteration 4, loss = 0.51499368
Validation score: 0.780941
Iteration 5, loss = 0.50032446
Validation score: 0.787311
Iteration 6, loss = 0.48875770
Validation score: 0.794285
Iteration 7, loss = 0.47942608
Validation score: 0.797452
Iteration 8, loss = 0.47112352
Validation score: 0.795815
Iteration 9, loss = 0.46449897
Validation score: 0.805388
Iteration 10, loss = 0.45811287
Validation score: 0.808590
Iteration 11, loss = 0.45244680
Validation score: 0.811330
Iteration 12, loss = 0.44708846
Validation score: 0.809978
Iteration 13, loss = 0.44114382
Validation score: 0.816526
Iteration 14, loss = 0.43669484
Validation score: 0.812825
Iteration 15, loss = 0.43251937
Validation score: 0.819088
Iteration 16, loss = 0.42858463
Validation score: 0.816170
Iteration 17, loss = 0.42432445
Validation score: 0.821543
Iterat

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=True, epsilon=1e-08,
       hidden_layer_sizes=100, learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=True, warm_start=False)

In [25]:
clf.score(scaled_test_data, test_labels)

0.87952